### ISSUE TITLE
Is this app redundant with CyanogenMod's "Start default music player when headphones are plugged in" ?

### ISSUE THREAD

**Issue by breversa** [vanilla-music/vanilla-headphone-detector#1]
Title says it all.

And if not… why ? :-)

**Comment by breversa** [comment]
Sorry, I worded my mind very poorly : I'm actually curious why Vanilla Music needs a specific app, when such an option exists (I actually don't think it's CM-specific anymore).

Also, without this app, Vanilla Music won't start when I plug my earphones with that option on.

So basically, my question sums up to : "Why doesn't Vanilla Music behave like an ordinary music player ?"

**Comment by adrian-bl** [comment]
Because this is not a standard AOSP feature. I didn't even know that CyanogenMod had it :-)

**Comment by breversa** [comment]
I have been using CyanogenMod for so long that I can no longer tell which feature is AOSP, and which isn't, but I do believe I saw that option on a non-CM ROM. :-)
Can anyone please confirm ?

Anyway, my question then changes to "why can't Vanilla be set as default music player ?".

**Comment by Almtesh** [comment]
Actually, I don't understand why this feature needs to be in a separate application.

**Comment by adrian-bl** [comment]
To save memory.
