### ISSUE TITLE
Release 1.7 not available F-Droid

### ISSUE THREAD

**Issue by CryptGoat** [vanilla-music/vanilla-headphone-detector#16]
The latest version 1.7 is still not available via F-Droid bug detected by the build server: https://f-droid.org/wiki/page/ch.blinkenlights.android.vanillaplug

Not sure what is wrong.

**Comment by breversa** [comment]
I made a new RFP for this : https://gitlab.com/fdroid/rfp/issues/964

**Comment by breversa** [comment]
RFP is not the right place for that.
I opened an issue instead : https://gitlab.com/fdroid/fdroiddata/issues/1606

**Comment by breversa** [comment]
Version 1.7 is now available on F-Droid : https://f-droid.org/fr/packages/ch.blinkenlights.android.vanillaplug/ since @adrian-bl added tags to the releases. :)

**Comment by PanderMusubi** [comment]
Please close this issue.
