### ISSUE TITLE
Ignores vanilla music's 'External Output only' setting

### ISSUE THREAD

**Issue by RunningDroid** [vanilla-music/vanilla-headphone-detector#2]
Sometimes when I unplug my headphones another headset_plug intent is fired and vanilla music starts playing even though I have 'External Output only' set.

**Comment by adrian-bl** [comment]
Thats more like a bug in your android ROM itself: I also see superfluent headset_plug events on my Xperia Z3 while the headphones are plugged in (so no harm is done - but still .. eh!).

While the 'External Output only' code is pretty hacky, i wouldn't be surprised if android really thinks that a headset was plugged in (as it just reported this event) while vanilla music queries the headset state.

Could you get me a logcat for this? Maybe there will be some additional clues about the issue - but i suspect that your ROM + Hardware are to blame :-/
