### ISSUE TITLE
Icon is too big

### ISSUE THREAD

**Issue by PanderMusubi** [vanilla-music/vanilla-headphone-detector#3]
The icon got a bit smaller for the new version of https://f-droid.org/repository/browse/?fdfilter=vanilla+music&fdid=ch.blinkenlights.android.vanilla

Please use the same dimensions for the icon at https://f-droid.org/repository/browse/?fdfilter=vanilla+music&fdid=ch.blinkenlights.android.vanillaplug and other places here and in the app.

**Comment by PanderMusubi** [comment]
See also https://github.com/vanilla-music/vanilla/blob/master/orig/icon.svgz

**Comment by bandali** [comment]
@PanderMusubi, I just merged @relan's beautiful new icon for the headphone detector that also matches his new materialized icon for the main app.

Closing this.
